# Generated by Django 4.1.5 on 2023-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(),
        ),
    ]
